---
title: "UKB alcohol T2D/HbA1c analysis"
output: html_document
---




```{r}
library(tidyverse)
library(SUMnlmr)
library(survival)
#devtools::install_github("harrelfe/rms")
install.packages("rms")
library(rms)

COX_update79<-readRDS("COX_update79.rds") #data prepared for survival analysis
update_pp679<-readRDS("update_pp679.rds") #data prepared for baseline prevalent analysis

```


Baseline prevalent cases analysis
```{r}
  update_pp679<-update_pp679 %>% dplyr::mutate(Sex_F=as.factor(Sex))
  update_pp679 <-update_pp679 %>% mutate(array_type=case_when(grepl("UKBiLEVEAX", Genotype.measurement.batch)~"UKBiLEVEAX", TRUE ~"Affy"))
  dummies_2<-model.matrix(~Sex, data=update_pp679 )[,2] 
  dummies_3<-model.matrix(~array_type, data=update_pp679 )[,2] 
  
summ_covar_FULL_T2D<-create_nlmr_summary(y = update_pp679$T2dX_at_BL,
                                 x = update_pp679$weekly_units_B_R,
                                 g = update_pp679$GRS_79,
                               covar=cbind(dummies_2,dummies_3,matrix(data=c(update_pp679$Age.at.recruitment, update_pp679$Genetic.principal.components...Array.1,update_pp679$Genetic.principal.components...Array.2,update_pp679$Genetic.principal.components...Array.3,update_pp679$Genetic.principal.components...Array.4,update_pp679$Genetic.principal.components...Array.5,update_pp679$Genetic.principal.components...Array.6,update_pp679$Genetic.principal.components...Array.7,update_pp679$Genetic.principal.components...Array.8,update_pp679$Genetic.principal.components...Array.9,update_pp679$Genetic.principal.components...Array.10),ncol=11)),
                                 family = "binomial",
                                 q = 10, strata_method="ranked", controlsonly = TRUE)

model_FULL_T2D<- with(summ_covar_FULL_T2D$summary, frac_poly_summ_mr(bx=bx,
                  by=by, 
                  bxse=bxse, 
                  byse=byse, 
                  xmean=xmean,
                  family="binomial",
                  fig=TRUE)
)
summary(model_FULL_T2D)
model_FULL_T2D <-with(summ_covar_FULL_T2D$summary, piecewise_summ_mr(by, bx, byse, bxse, xmean, xmin,xmax, 
                  ci="bootstrap_se",
                  nboot=1000, 
                  fig=TRUE,
                  family="binomial",
                  ci_fig="ribbon")
)
summary(model_FULL_T2D)

#now re-doing above with current drinkers AND NEVER DRINKERS only
df_DR<-update_pp679 %>% filter(BL_drinker_status=="Current"|BL_drinker_status=="Never")
dummies_2<-model.matrix(~Sex, data=df_DR)[,2] 
  dummies_3<-model.matrix(~array_type, data=df_DR)[,2] 
  summ_covar_DR_T2D<-create_nlmr_summary(y = df_DR$T2dX_at_BL,
                                 x = df_DR$weekly_units_B_R,
                                 g = df_DR$GRS_79,
                               covar=cbind(dummies_2,dummies_3,matrix(data=c(df_DR$Age.at.recruitment, df_DR$Genetic.principal.components...Array.1,df_DR$Genetic.principal.components...Array.2,df_DR$Genetic.principal.components...Array.3,df_DR$Genetic.principal.components...Array.4,df_DR$Genetic.principal.components...Array.5,df_DR$Genetic.principal.components...Array.6,df_DR$Genetic.principal.components...Array.7,df_DR$Genetic.principal.components...Array.8,df_DR$Genetic.principal.components...Array.9,df_DR$Genetic.principal.components...Array.10),ncol=11)),
                                 family = "binomial",
                                 q = 10, strata_method="ranked", controlsonly = TRUE)
  model_DR_T2D<- with(summ_covar_DR_T2D$summary, frac_poly_summ_mr(bx=bx,
                  by=by, 
                  bxse=bxse, 
                  byse=byse, 
                  xmean=xmean,
                  family="binomial",
                  fig=TRUE)
)
summary(model_DR_T2D)
model_DR_T2D <-with(summ_covar_DR_T2D$summary, piecewise_summ_mr(by, bx, byse, bxse, xmean, xmin,xmax, 
                  ci="bootstrap_se",
                  nboot=1000, 
                  fig=TRUE,
                  family="binomial",
                  ci_fig="ribbon")
)
summary(model_DR_T2D)

#to run above with current drinkers only:
df_DR<-update_pp679 %>% filter(BL_drinker_status=="Current")
#then re-run above lines

```


now repeat above for hba1c outcome
```{r}

sum(is.na(update_pp679$HbA1c_BL_winsor))
#need to remove everyone who is NA for that var 
#update_pp679 %>% count(Sex)
update_pp679<-update_pp679 %>% dplyr::mutate(Sex_F=as.factor(Sex))
  update_pp679 <-update_pp679 %>% mutate(array_type=case_when(grepl("UKBiLEVEAX", Genotype.measurement.batch)~"UKBiLEVEAX", TRUE ~"Affy"))
  full_HbA1c<-update_pp679 %>% filter(!is.na(HbA1c_BL_winsor))
  #women only
  full_HbA1c_F<-full_HbA1c %>% filter(Sex=="Female")
  #men only
   full_HbA1c_M<-full_HbA1c %>% filter(Sex=="Male")
  

dummies_2<-model.matrix(~Sex, data=full_HbA1c)[,2] 
  dummies_3<-model.matrix(~array_type, data=full_HbA1c)[,2] 
  

summ_covar_FULL_HB<-create_nlmr_summary(y = full_HbA1c$HbA1c_BL_winsor,
                                 x = full_HbA1c$weekly_units_B_R,
                                 g = full_HbA1c$GRS_79,
                               covar=cbind(dummies_2,dummies_3,matrix(data=c(full_HbA1c$Age.at.recruitment, full_HbA1c$Genetic.principal.components...Array.1,full_HbA1c$Genetic.principal.components...Array.2,full_HbA1c$Genetic.principal.components...Array.3,full_HbA1c$Genetic.principal.components...Array.4,full_HbA1c$Genetic.principal.components...Array.5,full_HbA1c$Genetic.principal.components...Array.6,full_HbA1c$Genetic.principal.components...Array.7,full_HbA1c$Genetic.principal.components...Array.8,full_HbA1c$Genetic.principal.components...Array.9,full_HbA1c$Genetic.principal.components...Array.10),ncol=11)),
                                 family = "gaussian",
                                 q = 10, strata_method="ranked", controlsonly = FALSE)
#MUST REMEMBER TO LOAD METAFOR LIBRARY BEFORE RUN MY VERSION OF THE FUNCTION!
#rather than having to remake function, simply override pref_y below
#also need to add ref values based on mean of lowest category for the fp (1.33), and min (0) for the piecewise
model_FULL_HB<- with(summ_covar_FULL_HB$summary, frac_poly_summ_mrRV(bx=bx,
                  by=by, 
                  bxse=bxse, 
                  byse=byse, 
                  xmean=xmean,
                  ref=1.33,
                  pref_y = "Relative HbA1c, mmol/mol",
                  family="gaussian",
                  fig=TRUE,ylim_lower = -2.1, ylim_upper = 0, breaks= c(-2,-1.5,-1,-.5,0))
)
model_FULL_HB

summary(model_FULL_HB) 
sum_test<-summary(model_FULL_HB) 
xvals<-model_FULL_HB[["figure"]][["data"]][["x"]]
yvals<-model_FULL_HB[["figure"]][["data"]][["yest"]]
uci<-model_FULL_HB[["figure"]][["data"]][["uci"]]
xyvals<-data.frame(xvals,yvals,uci) 
#for nadir index
which.min(xyvals$yvals)
xyvals[8539,]

model_FULL_HB <-with(summ_covar_FULL_HB$summary, piecewise_summ_mrRV(by, bx, byse, bxse, xmean, xmin,xmax, 
                  ci="bootstrap_se",
                  nboot=1000, 
                  fig=TRUE,
                  family="gaussian",
                      pref_y = "Relative HbA1c, mmol/mol",
                  ci_fig="ribbon")
)
summary(model_FULL_HB)

#now re-dpoing above with current drinkers AND NEVER DRINKERS only
DR_HbA1c<-full_HbA1c %>% filter(BL_drinker_status=="Never"|BL_drinker_status=="Current")
#15.05 doing as well for current drinkers only
DR_HbA1c<-full_HbA1c %>% filter(BL_drinker_status=="Current")

dummies_2<-model.matrix(~Sex, data=DR_HbA1c)[,2] 
  dummies_3<-model.matrix(~array_type, data=DR_HbA1c)[,2] 

  summ_covar_DR_HB<-create_nlmr_summary(y = DR_HbA1c$HbA1c_BL_winsor,
                                 x = DR_HbA1c$weekly_units_B_R,
                                 g = DR_HbA1c$GRS_79,
                               covar=cbind(dummies_2,dummies_3,matrix(data=c(DR_HbA1c$Age.at.recruitment, DR_HbA1c$Genetic.principal.components...Array.1,DR_HbA1c$Genetic.principal.components...Array.2,DR_HbA1c$Genetic.principal.components...Array.3,DR_HbA1c$Genetic.principal.components...Array.4,DR_HbA1c$Genetic.principal.components...Array.5,DR_HbA1c$Genetic.principal.components...Array.6,DR_HbA1c$Genetic.principal.components...Array.7,DR_HbA1c$Genetic.principal.components...Array.8,DR_HbA1c$Genetic.principal.components...Array.9,DR_HbA1c$Genetic.principal.components...Array.10),ncol=11)),
                                 family = "gaussian",
                                 q = 10, strata_method="ranked", controlsonly = FALSE)
  #rather than having to remake function, simply override pref_y below
  model_DR_HB<- with(summ_covar_DR_HB$summary, frac_poly_summ_mrRV(bx=bx,
                  by=by, 
                  bxse=bxse, 
                  byse=byse, 
                  xmean=xmean,
                  ref=2.85,  #ref=2.85 when current drinkers only
                  family="gaussian",
                   pref_y = "Relative HbA1c, mmol/mol",
                  fig=TRUE)
)
summary(model_DR_HB)


model_DR_HB <-with(summ_covar_DR_HB$summary, piecewise_summ_mrRV(by, bx, byse, bxse, xmean, xmin,xmax, 
                  ci="bootstrap_se",
                  nboot=1000, 
                  fig=TRUE,
                  ref=.47,
                  family="gaussian",
                   pref_y = "Relative HbA1c, mmol/mol",
                  ci_fig="ribbon")
)
summary(model_DR_HB)



#split further by BMI category
full_HbA1c_F<-full_HbA1c_F %>% filter(!is.na(Body.mass.index..BMI....Instance.0.participant...p21001_i0.))
full_HbA1c_F_N<-full_HbA1c_F %>% filter(Body.mass.index..BMI....Instance.0.participant...p21001_i0.<25) 
full_HbA1c_F_OV<-full_HbA1c_F %>% filter(Body.mass.index..BMI....Instance.0.participant...p21001_i0.>=25
                                             &Body.mass.index..BMI....Instance.0.participant...p21001_i0.<30)
full_HbA1c_F_OB<-full_HbA1c_F %>% filter(Body.mass.index..BMI....Instance.0.participant...p21001_i0.>30) 

#stratify on residual BMI instead
#step one is to regress BMI on the PRS
sum(is.na(full_HbA1c_F$Body.mass.index..BMI....Instance.0.participant...p21001_i0.)) 
sum(is.na(COX_update79_F$Body.mass.index..BMI....Instance.0.participant...p21001_i0.))  
full_HbA1c_F<-full_HbA1c_F %>% filter(!is.na(Body.mass.index..BMI....Instance.0.participant...p21001_i0.))
HBREG<-lm(Body.mass.index..BMI....Instance.0.participant...p21001_i0.~GRS_79, data=full_HbA1c_F )
full_HbA1c_F$value_lm <- HBREG$fitted.values
full_HbA1c_F<-full_HbA1c_F %>% mutate(resid_BMI=Body.mass.index..BMI....Instance.0.participant...p21001_i0.-value_lm)
range(full_HbA1c_F$resid_BMI) #these numbers are no longer meaningful in terms of BMI cut-offs, but instead we'll use tertiles
tertiles <- quantile(full_HbA1c_F$resid_BMI, probs=c(.333, .666), na.rm = FALSE)
full_HbA1c_F_N<-full_HbA1c_F %>% filter(resid_BMI <= -2.54) 
full_HbA1c_F_OV<-full_HbA1c_F %>% filter(resid_BMI > -2.54
                                             &resid_BMI <1.15) 
full_HbA1c_F_OB<-full_HbA1c_F %>% filter(resid_BMI >= 1.15) 


#doing the hba1c analysis stratified by sex


  dummies_3<-model.matrix(~array_type, data=full_HbA1c_M)[,2] 
  
summ_covar_F_NULL_HB<-create_nlmr_summary(y = full_HbA1c_M$HbA1c_BL_winsor,
                                 x = full_HbA1c_M$weekly_units_B_R,
                                 g = full_HbA1c_M$GRS_79,
                               covar=cbind(dummies_3,matrix(data=c(full_HbA1c_M$Age.at.recruitment, full_HbA1c_M$Genetic.principal.components...Array.1,full_HbA1c_M$Genetic.principal.components...Array.2,full_HbA1c_M$Genetic.principal.components...Array.3,full_HbA1c_M$Genetic.principal.components...Array.4,full_HbA1c_M$Genetic.principal.components...Array.5,full_HbA1c_M$Genetic.principal.components...Array.6,full_HbA1c_M$Genetic.principal.components...Array.7,full_HbA1c_M$Genetic.principal.components...Array.8,full_HbA1c_M$Genetic.principal.components...Array.9,full_HbA1c_M$Genetic.principal.components...Array.10),ncol=11)),
                                 family = "gaussian",
                                 q = 10, strata_method="ranked", controlsonly = FALSE)


#ref should be .755 for women; 2.63 for men 
#for F N should be 1.08; .853 for OV; .307 for OB
#using tertiles FN 1.09 FOV .988 F OB should be .42
model_FULL_HB<- with(summ_covar_F_NULL_HB$summary, frac_poly_summ_mrRV(bx=bx, 
                  by=by, 
                  bxse=bxse, 
                  byse=byse, 
                  ref=2.63,
                  xmean=xmean,
                  family="gaussian",
                  pref_y = "Relative HbA1c, mmol/mol",
                  fig=TRUE, ,ylim_lower = -2.1, ylim_upper = 0, breaks= c(-2,-1.5,-1,-.5,0)) 
) 
model_FULL_HB

sumMO<- summary(model_FULL_HB) 
max(model_FULL_HB[["figure"]][["data"]][["x"]]) 
sumMO[["figure"]]+ scale_x_continuous(breaks=seq(0,60,5))

```





```{r}


  update_pp679<-update_pp679 %>% dplyr::mutate(Sex_F=as.factor(Sex))
  update_pp679 <-update_pp679 %>% mutate(array_type=case_when(grepl("UKBiLEVEAX", Genotype.measurement.batch)~"UKBiLEVEAX", TRUE ~"Affy"))
  dummies_2<-model.matrix(~Sex, data=update_pp679 )[,2] 
  dummies_3<-model.matrix(~array_type, data=update_pp679 )[,2] 
  
summ_covar_FULL_T2D<-create_nlmr_summary(y = update_pp679$T2dX_at_BL,
                                 x = update_pp679$weekly_units_B_R,
                                 g = update_pp679$GRS_79,
                               covar=cbind(dummies_2,dummies_3,matrix(data=c(update_pp679$Age.at.recruitment, update_pp679$Genetic.principal.components...Array.1,update_pp679$Genetic.principal.components...Array.2,update_pp679$Genetic.principal.components...Array.3,update_pp679$Genetic.principal.components...Array.4,update_pp679$Genetic.principal.components...Array.5,update_pp679$Genetic.principal.components...Array.6,update_pp679$Genetic.principal.components...Array.7,update_pp679$Genetic.principal.components...Array.8,update_pp679$Genetic.principal.components...Array.9,update_pp679$Genetic.principal.components...Array.10),ncol=11)),
                                 family = "binomial",
                                 q = 10, strata_method="ranked", controlsonly = TRUE)

model_FULL_T2D<- with(summ_covar_FULL_T2D$summary, frac_poly_summ_mr(bx=bx,
                  by=by, 
                  bxse=bxse, 
                  byse=byse, 
                  xmean=xmean,
                  family="binomial",
                  fig=TRUE)
)
summary(model_FULL_T2D)
model_FULL_T2D <-with(summ_covar_FULL_T2D$summary, piecewise_summ_mr(by, bx, byse, bxse, xmean, xmin,xmax, 
                  ci="bootstrap_se",
                  nboot=1000, 
                  fig=TRUE,
                  family="binomial",
                  ci_fig="ribbon")
)
summary(model_FULL_T2D)

#now re-dpoing above with current drinkers AND NEVER DRINKERS only
df_DR<-update_pp679 %>% filter(BL_drinker_status=="Current"|BL_drinker_status=="Never")
dummies_2<-model.matrix(~Sex, data=df_DR)[,2] 
  dummies_3<-model.matrix(~array_type, data=df_DR)[,2] 
  summ_covar_DR_T2D<-create_nlmr_summary(y = df_DR$T2dX_at_BL,
                                 x = df_DR$weekly_units_B_R,
                                 g = df_DR$GRS_79,
                               covar=cbind(dummies_2,dummies_3,matrix(data=c(df_DR$Age.at.recruitment, df_DR$Genetic.principal.components...Array.1,df_DR$Genetic.principal.components...Array.2,df_DR$Genetic.principal.components...Array.3,df_DR$Genetic.principal.components...Array.4,df_DR$Genetic.principal.components...Array.5,df_DR$Genetic.principal.components...Array.6,df_DR$Genetic.principal.components...Array.7,df_DR$Genetic.principal.components...Array.8,df_DR$Genetic.principal.components...Array.9,df_DR$Genetic.principal.components...Array.10),ncol=11)),
                                 family = "binomial",
                                 q = 10, strata_method="ranked", controlsonly = TRUE)
  model_DR_T2D<- with(summ_covar_DR_T2D$summary, frac_poly_summ_mr(bx=bx,
                  by=by, 
                  bxse=bxse, 
                  byse=byse, 
                  xmean=xmean,
                  family="binomial",
                  fig=TRUE)
)
summary(model_DR_T2D)
model_DR_T2D <-with(summ_covar_DR_T2D$summary, piecewise_summ_mr(by, bx, byse, bxse, xmean, xmin,xmax, 
                  ci="bootstrap_se",
                  nboot=1000, 
                  fig=TRUE,
                  family="binomial",
                  ci_fig="ribbon")
)
summary(model_DR_T2D)

#09.05 Amy comment -> redo above with drinkers only

df_DR<-update_pp679 %>% filter(BL_drinker_status=="Current")
#then re-run above lines

```



#now repeat above for our two continuous measures
#HbA1c_BL_winsor
```{r}

sum(is.na(update_pp679$HbA1c_BL_winsor))
#need to remove everyone who is NA for that var 
#update_pp679 %>% count(Sex)
update_pp679<-update_pp679 %>% dplyr::mutate(Sex_F=as.factor(Sex))
  update_pp679 <-update_pp679 %>% mutate(array_type=case_when(grepl("UKBiLEVEAX", Genotype.measurement.batch)~"UKBiLEVEAX", TRUE ~"Affy"))
  full_HbA1c<-update_pp679 %>% filter(!is.na(HbA1c_BL_winsor))
  #women only
  full_HbA1c_F<-full_HbA1c %>% filter(Sex=="Female")
  #men only
   full_HbA1c_M<-full_HbA1c %>% filter(Sex=="Male")
  

dummies_2<-model.matrix(~Sex, data=full_HbA1c)[,2] 
  dummies_3<-model.matrix(~array_type, data=full_HbA1c)[,2] 
  

summ_covar_FULL_HB<-create_nlmr_summary(y = full_HbA1c$HbA1c_BL_winsor,
                                 x = full_HbA1c$weekly_units_B_R,
                                 g = full_HbA1c$GRS_79,
                               covar=cbind(dummies_2,dummies_3,matrix(data=c(full_HbA1c$Age.at.recruitment, full_HbA1c$Genetic.principal.components...Array.1,full_HbA1c$Genetic.principal.components...Array.2,full_HbA1c$Genetic.principal.components...Array.3,full_HbA1c$Genetic.principal.components...Array.4,full_HbA1c$Genetic.principal.components...Array.5,full_HbA1c$Genetic.principal.components...Array.6,full_HbA1c$Genetic.principal.components...Array.7,full_HbA1c$Genetic.principal.components...Array.8,full_HbA1c$Genetic.principal.components...Array.9,full_HbA1c$Genetic.principal.components...Array.10),ncol=11)),
                                 family = "gaussian",
                                 q = 10, strata_method="ranked", controlsonly = FALSE)
#MUST REMEMBER TO LOAD METAFOR LIBRARY BEFORE RUN MY VERSION OF THE FUNCTION!
#rather than having to remake function, simply override pref_y below
#also need to add ref values based on mean of lowest category for the fp (1.33), and min (0) for the piecewise
model_FULL_HB<- with(summ_covar_FULL_HB$summary, frac_poly_summ_mrRV(bx=bx,
                  by=by, 
                  bxse=bxse, 
                  byse=byse, 
                  xmean=xmean,
                  ref=1.33,
                  pref_y = "Relative HbA1C, mmol/mol",
                  family="gaussian",
                  fig=TRUE)
)
summary(model_FULL_HB) 
sum_test<-summary(model_FULL_HB) 
xvals<-model_FULL_HB[["figure"]][["data"]][["x"]]
yvals<-model_FULL_HB[["figure"]][["data"]][["yest"]]
uci<-model_FULL_HB[["figure"]][["data"]][["uci"]]
xyvals<-data.frame(xvals,yvals,uci) 
#for nadir index
which.min(xyvals$yvals)
xyvals[8539,]

model_FULL_HB <-with(summ_covar_FULL_HB$summary, piecewise_summ_mrRV(by, bx, byse, bxse, xmean, xmin,xmax, 
                  ci="bootstrap_se",
                  nboot=1000, 
                  fig=TRUE,
                  family="gaussian",
                      pref_y = "Relative HbA1C, mmol/mol",
                  ci_fig="ribbon")
)
summary(model_FULL_HB)

#now re-dpoing above with current drinkers AND NEVER DRINKERS only
DR_HbA1c<-full_HbA1c %>% filter(BL_drinker_status=="Never"|BL_drinker_status=="Current")
#15.05 doing as well for current drinkers only
DR_HbA1c<-full_HbA1c %>% filter(BL_drinker_status=="Current")

dummies_2<-model.matrix(~Sex, data=DR_HbA1c)[,2] 
  dummies_3<-model.matrix(~array_type, data=DR_HbA1c)[,2] 

  summ_covar_DR_HB<-create_nlmr_summary(y = DR_HbA1c$HbA1c_BL_winsor,
                                 x = DR_HbA1c$weekly_units_B_R,
                                 g = DR_HbA1c$GRS_79,
                               covar=cbind(dummies_2,dummies_3,matrix(data=c(DR_HbA1c$Age.at.recruitment, DR_HbA1c$Genetic.principal.components...Array.1,DR_HbA1c$Genetic.principal.components...Array.2,DR_HbA1c$Genetic.principal.components...Array.3,DR_HbA1c$Genetic.principal.components...Array.4,DR_HbA1c$Genetic.principal.components...Array.5,DR_HbA1c$Genetic.principal.components...Array.6,DR_HbA1c$Genetic.principal.components...Array.7,DR_HbA1c$Genetic.principal.components...Array.8,DR_HbA1c$Genetic.principal.components...Array.9,DR_HbA1c$Genetic.principal.components...Array.10),ncol=11)),
                                 family = "gaussian",
                                 q = 10, strata_method="ranked", controlsonly = FALSE)
  #rather than having to remake function, simply override pref_y below
  model_DR_HB<- with(summ_covar_DR_HB$summary, frac_poly_summ_mrRV(bx=bx,
                  by=by, 
                  bxse=bxse, 
                  byse=byse, 
                  xmean=xmean,
                  ref=2.85,  #ref=2.85 when current drinkers only
                  family="gaussian",
                   pref_y = "Relative HbA1C, mmol/mol",
                  fig=TRUE)
)
summary(model_DR_HB)


model_DR_HB <-with(summ_covar_DR_HB$summary, piecewise_summ_mrRV(by, bx, byse, bxse, xmean, xmin,xmax, 
                  ci="bootstrap_se",
                  nboot=1000, 
                  fig=TRUE,
                  ref=.47,
                  family="gaussian",
                   pref_y = "Relative HbA1C, mmol/mol",
                  ci_fig="ribbon")
)
summary(model_DR_HB)



#24.04 doing the hba1c analysis stratified by sex
#dummies_2<-model.matrix(~Sex, data=full_HbA1c)[,2] 

  dummies_3<-model.matrix(~array_type, data=full_HbA1c_F)[,2] 
  
summ_covar_FULL_HB<-create_nlmr_summary(y = full_HbA1c_F$HbA1c_BL_winsor,
                                 x = full_HbA1c_F$weekly_units_B_R,
                                 g = full_HbA1c_F$GRS_79,
                               covar=cbind(dummies_3,matrix(data=c(full_HbA1c_F$Age.at.recruitment, full_HbA1c_F$Genetic.principal.components...Array.1,full_HbA1c_F$Genetic.principal.components...Array.2,full_HbA1c_F$Genetic.principal.components...Array.3,full_HbA1c_F$Genetic.principal.components...Array.4,full_HbA1c_F$Genetic.principal.components...Array.5,full_HbA1c_F$Genetic.principal.components...Array.6,full_HbA1c_F$Genetic.principal.components...Array.7,full_HbA1c_F$Genetic.principal.components...Array.8,full_HbA1c_F$Genetic.principal.components...Array.9,full_HbA1c_F$Genetic.principal.components...Array.10),ncol=11)),
                                 family = "gaussian",
                                 q = 10, strata_method="ranked", controlsonly = FALSE)


#ref should be .755 for women; 2.63 for men 
model_FULL_HB<- with(summ_covar_FULL_HB$summary, frac_poly_summ_mrRV(bx=bx, #can see the problem occurs here -> powers are 1 and 1
                  by=by, 
                  bxse=bxse, 
                  byse=byse, 
                  ref=.755,
                  xmean=xmean,
                  family="gaussian",
                  pref_y = "Relative HbA1C, mmol/mol",
                  fig=TRUE)
) 

sumMO<- summary(model_FULL_HB) #+ scale_x_continuous(breaks=seq(0,60,5))
max(model_FULL_HB[["figure"]][["data"]][["x"]]) #ahh ok can see here for female that the max x for the figure is 40.53 -> not sure why it only generated up to here -> ahh ok can see that what's happened is it takes the xmean from highest stratum
sumMO[["figure"]]+ scale_x_continuous(breaks=seq(0,60,5))
#hmm something's going wrong when try to apply my fp function above -> telling me the powers are 1 and 1 (X1 and X1.1) -> same for both female and male version
#hmm doing same thing when use the original frac_poly function too -> GOING TO LEAVE THIS FOR NOW AND HOPE IT FIXES BY THE TIME GET BACK TO IT
#update 17.05 -> is now working for males only (now matching original stats)! but same prob for females
```




Cox observational with spline term
```{r}


#these lines are essential for predict and plot.Predict functions
detach(COX_update79_noEx)
attach(COX_update79)
dd <- datadist(weekly_units_B_R, Sex_F, Age.at.recruitment, Past.tobacco.smoking...Instance.0,tert_deg,Townsend.deprivation.index.at.recruitment, Summed.MET.minutes.per.week.for.all.activity...Instance.0)
options(datadist='dd')
dd$limits["Adjust to","weekly_units_B_R"] <- 0 

survobj <- with(COX_update79, Surv(TIS,STATUS))
coxmod<-cph(survobj ~ rcs(weekly_units_B_R,3 )+ Sex_F+ Age.at.recruitment + Past.tobacco.smoking...Instance.0 +tert_deg +Townsend.deprivation.index.at.recruitment + Summed.MET.minutes.per.week.for.all.activity...Instance.0, data = COX_update79) #using 3 knots


p <- Predict(coxmod, weekly_units_B_R (),ref.zero=TRUE, 
              fun=exp) 
lsf.str("package:rms") #ok for some reason the plot.Predict function didn't come in with this, so have to define it myself using the github code

acttualplot<-plot.Predict(p, ~ weekly_units_B_R,
             col="black",
             col.fill=gray(seq(.8, .75, length=5)), xlab="Drinks per week", ylab="Hazard ratio of T2D", abline=list(h=1,lty=2)) 

#by sex
COX_update79_F<-COX_update79 %>% filter(Sex=="Female")
detach(COX_update79)
attach(COX_update79_F)
dd <- datadist(weekly_units_B_R, Age.at.recruitment, Past.tobacco.smoking...Instance.0,tert_deg,Townsend.deprivation.index.at.recruitment, Summed.MET.minutes.per.week.for.all.activity...Instance.0)
options(datadist='dd')
dd$limits["Adjust to","weekly_units_B_R"] <- 0 

survobj <- with(COX_update79_F, Surv(TIS,STATUS))
coxmod<-cph(survobj ~ rcs(weekly_units_B_R,3 )+ Age.at.recruitment + Past.tobacco.smoking...Instance.0 +tert_deg +Townsend.deprivation.index.at.recruitment + Summed.MET.minutes.per.week.for.all.activity...Instance.0, data = COX_update79_F) #using 3 knots

p <- Predict(coxmod, weekly_units_B_R (),ref.zero=TRUE, 
              fun=exp)
acttualplot<-plot.Predict(p, ~ weekly_units_B_R,
             col="black",
             col.fill=gray(seq(.8, .75, length=5)), xlab="Drinks per week", ylab="Hazard ratio of T2D", abline=list(h=1,lty=2)) 

COX_update79_M<-COX_update79 %>% filter(Sex=="Male")
detach(COX_update79_F)
attach(COX_update79_M)
dd <- datadist(weekly_units_B_R, Age.at.recruitment, Past.tobacco.smoking...Instance.0,tert_deg,Townsend.deprivation.index.at.recruitment, Summed.MET.minutes.per.week.for.all.activity...Instance.0)
options(datadist='dd')
dd$limits["Adjust to","weekly_units_B_R"] <- 0 

survobj <- with(COX_update79_M, Surv(TIS,STATUS))
coxmod<-cph(survobj ~ rcs(weekly_units_B_R,3 )+ Age.at.recruitment + Past.tobacco.smoking...Instance.0 +tert_deg +Townsend.deprivation.index.at.recruitment + Summed.MET.minutes.per.week.for.all.activity...Instance.0, data = COX_update79_M) #using 3 knots

p <- Predict(coxmod, weekly_units_B_R (),ref.zero=TRUE, 
              fun=exp)
acttualplot<-plot.Predict(p, ~ weekly_units_B_R,
             col="black",
             col.fill=gray(seq(.8, .75, length=5)), xlab="Drinks per week", ylab="Hazard ratio of T2D", abline=list(h=1,lty=2)) 

#and removing former drinkers > very similar results
COX_update79_noEx<-COX_update79 %>% filter(BL_drinker_status=="Never"|BL_drinker_status=="Current")
detach(COX_update79_M)
attach(COX_update79_noEx)
dd <- datadist(weekly_units_B_R, Sex_F, Age.at.recruitment, Past.tobacco.smoking...Instance.0,tert_deg,Townsend.deprivation.index.at.recruitment, Summed.MET.minutes.per.week.for.all.activity...Instance.0)
options(datadist='dd')
dd$limits["Adjust to","weekly_units_B_R"] <- 0 

survobj <- with(COX_update79_noEx, Surv(TIS,STATUS))
coxmod<-cph(survobj ~ rcs(weekly_units_B_R,3 )+ Sex_F+ Age.at.recruitment + Past.tobacco.smoking...Instance.0 +tert_deg +Townsend.deprivation.index.at.recruitment + Summed.MET.minutes.per.week.for.all.activity...Instance.0, data = COX_update79_noEx) #using 3 knots


#current drinkers only 
COX_update79_noEx<-COX_update79 %>% filter(BL_drinker_status=="Current")
detach(COX_update79_noEx)

```


```{r}
detach(package:SUMnlmr, unload = TRUE)
devtools::install_github("amymariemason/SUMnlmr") #reinstalling so can get latest version with cox option
library(SUMnlmr)

COX_update79_noEx<-COX_update79 %>% filter(BL_drinker_status=="Never"|BL_drinker_status=="Current")
#and with current drinkers only
COX_update79_noEx<-COX_update79 %>% filter(BL_drinker_status=="Current")


dummies_2<-model.matrix(~Sex, data=COX_update79)[,2] 
  dummies_3<-model.matrix(~array_type, data=COX_update79)[,2] 

summ_covar_FULL_T2D_COX<-SUMnlmr::create_nlmr_summary(
                                         y=COX_update79$survobj,
                                 x = COX_update79$weekly_units_B_R, 
                                 g = COX_update79$GRS_79,
                                 covar=cbind(dummies_2,dummies_3,matrix(data=c(COX_update79$Age.at.recruitment, COX_update79$Genetic.principal.components...Array.1,COX_update79$Genetic.principal.components...Array.2,COX_update79$Genetic.principal.components...Array.3,COX_update79$Genetic.principal.components...Array.4,COX_update79$Genetic.principal.components...Array.5,COX_update79$Genetic.principal.components...Array.6,COX_update79$Genetic.principal.components...Array.7,COX_update79$Genetic.principal.components...Array.8,COX_update79$Genetic.principal.components...Array.9,COX_update79$Genetic.principal.components...Array.10),ncol=11)),
                                 family = "coxph",
                                 q = 10, strata_method="ranked", controlsonly = FALSE) 
library(metafor)
library(stats)
library(matrixStats)
  model_DR_COX<- with(summ_covar_FULL_T2D_COX$summary, frac_poly_summ_mrRV(bx=bx,
                  by=by, 
                  bxse=bxse, 
                  byse=byse,
                  ref=1.34,
                  xmean=xmean,
                  family="cox",
                  fig=TRUE,  ylim_lower = .45, ylim_upper = 4.2, breaks= c(0.5,1,2,3))
)
summary(model_DR_COX)
#ok now to extract the NDE value
xvals<-model_DR_COX[["figure"]][["data"]][["x"]]
yvals<-model_DR_COX[["figure"]][["data"]][["yest"]]
uci<-model_DR_COX[["figure"]][["data"]][["uci"]]
xyvals<-data.frame(xvals,yvals,uci) 
which.min(xyvals$yvals)
xyvals[6358,]


model_DR_COX <-with(summ_covar_FULL_T2D_COX$summary, SUMnlmr::piecewise_summ_mr(by, bx, byse, bxse, xmean, xmin,xmax, 
                  ci="bootstrap_se",
                  nboot=1000, 
                  fig=TRUE,
                  ref=0,
                  family="cox",
                  ci_fig="ribbon")
)
summary(model_DR_COX)
LACESUM<-summary(model_DR_COX)

model_DR_COX <-with(summ_covar_FULL_T2D_COX$summary, piecewise_summ_mrRV(by, bx, byse, bxse, xmean, xmin,xmax, 
                  ci="bootstrap_se",
                  nboot=1000, 
                  fig=TRUE,
                  ref=1,
                  family="cox",
                  ci_fig="ribbon")
)
summary(model_DR_COX) 



library(tidyverse)
COX_update79 %>% count(Sex)
library(survival) 
COX_update79_noEx<-COX_update79 %>% filter(BL_drinker_status=="Current")
COX_update79_M<-COX_update79 %>% filter(Sex=="Male")
COX_update79_F<-COX_update79 %>% filter(Sex=="Female")


str_sort(names(COX_update79))
COX_update79_F_N<-COX_update79_F %>% filter(Body.mass.index..BMI....Instance.0.participant...p21001_i0.<25) 
COX_update79_F_OV<-COX_update79_F %>% filter(Body.mass.index..BMI....Instance.0.participant...p21001_i0.>=25
                                             &Body.mass.index..BMI....Instance.0.participant...p21001_i0.<30) 
COX_update79_F_OB<-COX_update79_F %>% filter(Body.mass.index..BMI....Instance.0.participant...p21001_i0.>30) 

# residual BMI instead
COX_update79_F<-COX_update79_F %>% filter(!is.na(Body.mass.index..BMI....Instance.0.participant...p21001_i0.))
HBREG<-lm(Body.mass.index..BMI....Instance.0.participant...p21001_i0.~GRS_79, data=COX_update79_F )
COX_update79_F$value_lm <- HBREG$fitted.values
COX_update79_F<-COX_update79_F %>% mutate(resid_BMI=Body.mass.index..BMI....Instance.0.participant...p21001_i0.-value_lm)
range(COX_update79_F$resid_BMI) #these numbers are no longer meaningful in terms of BMI cut-offs, but instead we'll use tertiles
tertiles <- quantile(COX_update79_F$resid_BMI, probs=c(.333, .666), na.rm = FALSE)
COX_update79_F_N<-COX_update79_F %>% filter(resid_BMI <= -2.51)
COX_update79_F_OV<-COX_update79_F %>% filter(resid_BMI > -2.51
                                             &resid_BMI <1.14) 
COX_update79_F_OB<-COX_update79_F %>% filter(resid_BMI >= 1.14) 

COX_update79_noEx_M<-COX_update79_noEx %>% filter(Sex=="Male")
COX_update79_noEx_F<-COX_update79_noEx %>% filter(Sex=="Female")

  dummies_3<-model.matrix(~array_type, data=COX_update79_F_OB)[,2] 

summ_covar_noEx_FULL_T2D_COX<-SUMnlmr::create_nlmr_summary(
                                         y=COX_update79_F_OB$survobj,
                                 x = COX_update79_F_OB$weekly_units_B_R, 
                                 g = COX_update79_F_OB$GRS_79,
                                 covar=cbind(dummies_3,matrix(data=c(COX_update79_F_OB$Age.at.recruitment, COX_update79_F_OB$Genetic.principal.components...Array.1,COX_update79_F_OB$Genetic.principal.components...Array.2,COX_update79_F_OB$Genetic.principal.components...Array.3,COX_update79_F_OB$Genetic.principal.components...Array.4,COX_update79_F_OB$Genetic.principal.components...Array.5,COX_update79_F_OB$Genetic.principal.components...Array.6,COX_update79_F_OB$Genetic.principal.components...Array.7,COX_update79_F_OB$Genetic.principal.components...Array.8,COX_update79_F_OB$Genetic.principal.components...Array.9,COX_update79_F_OB$Genetic.principal.components...Array.10),ncol=11)),
                                 family = "coxph",
                                 q = 10, strata_method="ranked", controlsonly = FALSE) 

  model_DR_COX<- with(summ_covar_noEx_FULL_T2D_COX$summary, frac_poly_summ_mrRV(bx=bx,
                  by=by, 
                  bxse=bxse, 
                  byse=byse,
                  ref=.439,
                  xmean=xmean,
                  family="cox",
                  fig=TRUE,ylim_lower = .19, ylim_upper = 1.5, breaks= c(0.2,.5,1, 1.5)  )) 
  
model_DR_COX  
  
summary(model_DR_COX)


model_DR_COX <-with(summ_covar_noEx_MULL_T2D_COX$summary, piecewise_summ_mrRV(by, bx, byse, bxse, xmean, xmin,xmax, 
                  ci="bootstrap_se",
                  nboot=1000, 
                  fig=TRUE,
                  ref=0,
                  family="cox",
                  ci_fig="ribbon")
)
summary(model_DR_COX)


#remove primary care diagnoses and see new results
str_sort(names(COX_update79)) #"Source.of.report.of.E11..non.insulin.dependent.diabetes.mellitus." 
temp<-COX_update79 %>% select(ID_1,"Source.of.report.of.E11..non.insulin.dependent.diabetes.mellitus." )
COX_update79<-COX_update79 %>% mutate(source_T2D=Source.of.report.of.E11..non.insulin.dependent.diabetes.mellitus.)
COX_update79 %>% dplyr::count(source_T2D) #vast majority of T2D diags are from hospital admissions


#now remove those diagnosed through primary care only and primary care and other source(s)
COX_update79<-COX_update79 %>% filter(source_T2D!="Primary care only")
COX_update79<-COX_update79 %>% filter(source_T2D!="Primary care and other source(s)")
#now re-run main Cox 
dummies_2<-model.matrix(~Sex, data=COX_update79)[,2] 
  dummies_3<-model.matrix(~array_type, data=COX_update79)[,2] 

summ_covar_FULL_T2D_COX<-SUMnlmr::create_nlmr_summary(
                                         y=COX_update79$survobj,
                                 x = COX_update79$weekly_units_B_R, 
                                 g = COX_update79$GRS_79,
                                 covar=cbind(dummies_2,dummies_3,matrix(data=c(COX_update79$Age.at.recruitment, COX_update79$Genetic.principal.components...Array.1,COX_update79$Genetic.principal.components...Array.2,COX_update79$Genetic.principal.components...Array.3,COX_update79$Genetic.principal.components...Array.4,COX_update79$Genetic.principal.components...Array.5,COX_update79$Genetic.principal.components...Array.6,COX_update79$Genetic.principal.components...Array.7,COX_update79$Genetic.principal.components...Array.8,COX_update79$Genetic.principal.components...Array.9,COX_update79$Genetic.principal.components...Array.10),ncol=11)),
                                 family = "coxph",
                                 q = 10, strata_method="ranked", controlsonly = FALSE) 


  model_DR_COX<- with(summ_covar_FULL_T2D_COX$summary, frac_poly_summ_mrRV(bx=bx,
                  by=by, 
                  bxse=bxse, 
                  byse=byse,
                  ref=1.36,
                  xmean=xmean,
                  family="cox",
                  fig=TRUE
                                )
)
summary(model_DR_COX)
#ok now to extract the NDE value
xvals<-model_DR_COX[["figure"]][["data"]][["x"]]
yvals<-model_DR_COX[["figure"]][["data"]][["yest"]]
uci<-model_DR_COX[["figure"]][["data"]][["uci"]]
lci<-model_DR_COX[["figure"]][["data"]][["lci"]]
xyvals<-data.frame(xvals,yvals,uci, lci) 
which.min(xyvals$yvals)
xyvals[6766,]

model_DR_COX <-with(summ_covar_FULL_T2D_COX$summary, piecewise_summ_mrRV(by, bx, byse, bxse, xmean, xmin,xmax, 
                  ci="bootstrap_se",
                  nboot=1000, 
                  fig=TRUE,
                  ref=0,
                  family="cox",
                  ci_fig="ribbon")
)
summary(model_DR_COX)

```




